import os

from dotenv import load_dotenv


load_dotenv()

DJANGO_SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME")
OPENAI_TEMPERATURE_MODEL = os.getenv("OPENAI_TEMPERATURE_MODEL")
PROMPT_SYSTEM_GAME_DESCRIPTION = os.getenv("PROMPT_SYSTEM_GAME_DESCRIPTION")
PROMPT_USER_GAME_DESCRIPTION = os.getenv("PROMPT_USER_GAME_DESCRIPTION")
